# Generated by Django 3.2 on 2024-09-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textextracter', '0002_auto_20240903_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
