# Generated by Django 3.2 on 2024-09-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textextracter', '0003_alter_customuser_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
